apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <job-name>
spec:
  schedule: "<ron expression/rate>"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: businessMetricsPlotter
            image: <businessMetricsPlotter Image>
            env:
            - name: DATABASENAME
              value: <database name to be used from data science's datautils>
            - name: QUERY
              value: <query to execute>
            - name: NAMESPACE
              value: <Namespace to plot under in cloudwatch>
            - name: METRICNAME
              value: <column name to be used as value>
          restartPolicy: Never
  concurrencyPolicy: Forbid